//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextToScreen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localisation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextToScreen.Properties.Localisation", typeof(Localisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new song....
        /// </summary>
        internal static string AddFileWindowTitle {
            get {
                return ResourceManager.GetString("AddFileWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected archive contains unknown file types..
        /// </summary>
        internal static string ArchiveContainsUnsupportedFiles {
            get {
                return ResourceManager.GetString("ArchiveContainsUnsupportedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save following songs because an error was encountered while saving them:
        ///
        ///.
        /// </summary>
        internal static string ArchiveFilesFailedToSaveHeader {
            get {
                return ResourceManager.GetString("ArchiveFilesFailedToSaveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify archive path before reading or writing to drive.
        /// </summary>
        internal static string ArchivePathNullException {
            get {
                return ResourceManager.GetString("ArchivePathNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No group.
        /// </summary>
        internal static string DefaultGroupName {
            get {
                return ResourceManager.GetString("DefaultGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string DefaultLanguage {
            get {
                return ResourceManager.GetString("DefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following files were not imported because of respective reasons:.
        /// </summary>
        internal static string FileImportProblemsHeader {
            get {
                return ResourceManager.GetString("FileImportProblemsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files imported successfully..
        /// </summary>
        internal static string FileImportSuccessfulCount {
            get {
                return ResourceManager.GetString("FileImportSuccessfulCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File import.
        /// </summary>
        internal static string FileImportTitle {
            get {
                return ResourceManager.GetString("FileImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        internal static string FileListView_GroupBox_ShowAll {
            get {
                return ResourceManager.GetString("FileListView_GroupBox_ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your filters do not match any songs.
        /// </summary>
        internal static string FileListView_NothingMatched {
            get {
                return ResourceManager.GetString("FileListView_NothingMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was not found on the drive.
        /// </summary>
        internal static string FileNotFoundOnDisk {
            get {
                return ResourceManager.GetString("FileNotFoundOnDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different values.
        /// </summary>
        internal static string FilePropertiesViewer_DifferentValues {
            get {
                return ResourceManager.GetString("FilePropertiesViewer_DifferentValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomoc.chm.
        /// </summary>
        internal static string HelpFilePath {
            get {
                return ResourceManager.GetString("HelpFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported from .sng.
        /// </summary>
        internal static string ImportCommentSng {
            get {
                return ResourceManager.GetString("ImportCommentSng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported from .txt.
        /// </summary>
        internal static string ImportCommentTxt {
            get {
                return ResourceManager.GetString("ImportCommentTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported from an archive.
        /// </summary>
        internal static string ImportCommentZip {
            get {
                return ResourceManager.GetString("ImportCommentZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported songs.
        /// </summary>
        internal static string ImportGroupName {
            get {
                return ResourceManager.GetString("ImportGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown file format or empty file.
        /// </summary>
        internal static string InvalidFileFormat {
            get {
                return ResourceManager.GetString("InvalidFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change the language you have to restart the application..
        /// </summary>
        internal static string Message_RestartNeeded_Text {
            get {
                return ResourceManager.GetString("Message_RestartNeeded_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language change.
        /// </summary>
        internal static string Message_RestartNeeded_Title {
            get {
                return ResourceManager.GetString("Message_RestartNeeded_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is already running. If you want to  restart the application close the running instance first..
        /// </summary>
        internal static string MessageBoxes_ApplicationAlreadyRunningInfo_Message {
            get {
                return ResourceManager.GetString("MessageBoxes_ApplicationAlreadyRunningInfo_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is already running.
        /// </summary>
        internal static string MessageBoxes_ApplicationAlreadyRunningInfo_Title {
            get {
                return ResourceManager.GetString("MessageBoxes_ApplicationAlreadyRunningInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened archive has been modified by another application. Do you want to reload it? (all non-saved changes will be discarded).
        /// </summary>
        internal static string MessageBoxes_ArchiveContentsChangedExternally_Message {
            get {
                return ResourceManager.GetString("MessageBoxes_ArchiveContentsChangedExternally_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive changed by external application.
        /// </summary>
        internal static string MessageBoxes_ArchiveContentsChangedExternally_Title {
            get {
                return ResourceManager.GetString("MessageBoxes_ArchiveContentsChangedExternally_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive &quot;{0}&quot; doesn&apos;t exist.
        /// </summary>
        internal static string MessageBoxes_ArchiveDoesNotExist_Message {
            get {
                return ResourceManager.GetString("MessageBoxes_ArchiveDoesNotExist_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open error.
        /// </summary>
        internal static string MessageBoxes_ArchiveDoesNotExist_Title {
            get {
                return ResourceManager.GetString("MessageBoxes_ArchiveDoesNotExist_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened archive has been moved or its name has been changed by another application. Do you want to update the archive path?.
        /// </summary>
        internal static string MessageBoxes_ArchiveNameChangedExternally_Message {
            get {
                return ResourceManager.GetString("MessageBoxes_ArchiveNameChangedExternally_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive changed by external application.
        /// </summary>
        internal static string MessageBoxes_ArchiveNameChangedExternally_Title {
            get {
                return ResourceManager.GetString("MessageBoxes_ArchiveNameChangedExternally_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the first start of TTS or the settings have been reset. Do you want to view help?.
        /// </summary>
        internal static string MessageBoxes_FirstStartQuestion_Message {
            get {
                return ResourceManager.GetString("MessageBoxes_FirstStartQuestion_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First start.
        /// </summary>
        internal static string MessageBoxes_FirstStartQuestion_Title {
            get {
                return ResourceManager.GetString("MessageBoxes_FirstStartQuestion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied group name is invalid. Group name can&apos;t contain any of the following characters:.
        /// </summary>
        internal static string MessageBoxes_GroupIsInvalidInfo_Message {
            get {
                return ResourceManager.GetString("MessageBoxes_GroupIsInvalidInfo_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid group name.
        /// </summary>
        internal static string MessageBoxes_GroupIsInvalidInfo_Title {
            get {
                return ResourceManager.GetString("MessageBoxes_GroupIsInvalidInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected archive has invalid format or contains unsupported file types. If this archive does contain valid song files you can use the import tool to add them to a new archive..
        /// </summary>
        internal static string MessageBoxes_InvalidArchiveInfo_Message {
            get {
                return ResourceManager.GetString("MessageBoxes_InvalidArchiveInfo_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown archive format.
        /// </summary>
        internal static string MessageBoxes_InvalidArchiveInfo_Title {
            get {
                return ResourceManager.GetString("MessageBoxes_InvalidArchiveInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied song name is invalid. Group name can&apos;t contain any of the following characters:.
        /// </summary>
        internal static string MessageBoxes_NameIsInvalidInfo_Message {
            get {
                return ResourceManager.GetString("MessageBoxes_NameIsInvalidInfo_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid song name.
        /// </summary>
        internal static string MessageBoxes_NameIsInvalidInfo_Title {
            get {
                return ResourceManager.GetString("MessageBoxes_NameIsInvalidInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected name is already taken.
        /// </summary>
        internal static string MessageBoxes_NameIsTakenInfo_Message {
            get {
                return ResourceManager.GetString("MessageBoxes_NameIsTakenInfo_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name.
        /// </summary>
        internal static string MessageBoxes_NameIsTakenInfo_Title {
            get {
                return ResourceManager.GetString("MessageBoxes_NameIsTakenInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing was selected to export..
        /// </summary>
        internal static string MessageBoxes_NothingToExportInfo_Message {
            get {
                return ResourceManager.GetString("MessageBoxes_NothingToExportInfo_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export error.
        /// </summary>
        internal static string MessageBoxes_NothingToExportInfo_Title {
            get {
                return ResourceManager.GetString("MessageBoxes_NothingToExportInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing was selected to import..
        /// </summary>
        internal static string MessageBoxes_NothingToImportInfo_Message {
            get {
                return ResourceManager.GetString("MessageBoxes_NothingToImportInfo_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import error.
        /// </summary>
        internal static string MessageBoxes_NothingToImportInfo_Title {
            get {
                return ResourceManager.GetString("MessageBoxes_NothingToImportInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove selected songs?.
        /// </summary>
        internal static string MessageBoxes_RemoveSelectedFiles_Message {
            get {
                return ResourceManager.GetString("MessageBoxes_RemoveSelectedFiles_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete song files.
        /// </summary>
        internal static string MessageBoxes_RemoveSelectedFiles_Title {
            get {
                return ResourceManager.GetString("MessageBoxes_RemoveSelectedFiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to the opened archive before continuing? Unsaved changes will be lost..
        /// </summary>
        internal static string MessageBoxes_SaveChangesToOpenedArchive_Message {
            get {
                return ResourceManager.GetString("MessageBoxes_SaveChangesToOpenedArchive_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to opened archive.
        /// </summary>
        internal static string MessageBoxes_SaveChangesToOpenedArchive_Title {
            get {
                return ResourceManager.GetString("MessageBoxes_SaveChangesToOpenedArchive_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to the opened song before continuing? Unsaved changes will be lost..
        /// </summary>
        internal static string MessageBoxes_SaveChangesToOpenedFile_Message {
            get {
                return ResourceManager.GetString("MessageBoxes_SaveChangesToOpenedFile_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to opened song.
        /// </summary>
        internal static string MessageBoxes_SaveChangesToOpenedFile_Title {
            get {
                return ResourceManager.GetString("MessageBoxes_SaveChangesToOpenedFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied name contains invalid characters:.
        /// </summary>
        internal static string NameContainsInvalidChars {
            get {
                return ResourceManager.GetString("NameContainsInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied name is already taken.
        /// </summary>
        internal static string NameIsAlreadyTaken {
            get {
                return ResourceManager.GetString("NameIsAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied name is empty.
        /// </summary>
        internal static string NameIsEmpty {
            get {
                return ResourceManager.GetString("NameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New archive.
        /// </summary>
        internal static string NewArchiveDefaultName {
            get {
                return ResourceManager.GetString("NewArchiveDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New song.
        /// </summary>
        internal static string NewFileDefaultName {
            get {
                return ResourceManager.GetString("NewFileDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview screen.
        /// </summary>
        internal static string PreviewScreenInfo {
            get {
                return ResourceManager.GetString("PreviewScreenInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename song....
        /// </summary>
        internal static string RenameFileWindowTitle {
            get {
                return ResourceManager.GetString("RenameFileWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title: {0}, Modified: {1}, Added: {2}, Comment: {3}.
        /// </summary>
        internal static string SongFileArchive_ToString_Format {
            get {
                return ResourceManager.GetString("SongFileArchive_ToString_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string SongFileArchive_ToString_MissingComment {
            get {
                return ResourceManager.GetString("SongFileArchive_ToString_MissingComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file type.
        /// </summary>
        internal static string UnsupportedFileFormat {
            get {
                return ResourceManager.GetString("UnsupportedFileFormat", resourceCulture);
            }
        }
    }
}
