//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Collections.Specialized;
using System.Configuration;
using System.Diagnostics;
using System.Drawing;
using System.Runtime.CompilerServices;
using TextToScreen.Misc;

namespace TextToScreen.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Ustawienia : ApplicationSettingsBase {
        
        private static Ustawienia defaultInstance = ((Ustawienia)(ApplicationSettingsBase.Synchronized(new Ustawienia())));
        
        public static Ustawienia Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("MiddleCenter")]
        [SettingsManageability(SettingsManageability.Roaming)]
        public ContentAlignment ScreenFontAlignment {
            get {
                return ((ContentAlignment)(this["ScreenFontAlignment"]));
            }
            set {
                this["ScreenFontAlignment"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Arial")]
        [SettingsManageability(SettingsManageability.Roaming)]
        public string ScreenFontFamily {
            get {
                return ((string)(this["ScreenFontFamily"]));
            }
            set {
                this["ScreenFontFamily"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("20")]
        [SettingsManageability(SettingsManageability.Roaming)]
        public decimal ScreenFontSize {
            get {
                return ((decimal)(this["ScreenFontSize"]));
            }
            set {
                this["ScreenFontSize"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0, 0")]
        public Point AutoOknoGlownePozycja {
            get {
                return ((Point)(this["AutoOknoGlownePozycja"]));
            }
            set {
                this["AutoOknoGlownePozycja"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0, 0")]
        public Point AutoOknoDocelowePozycja {
            get {
                return ((Point)(this["AutoOknoDocelowePozycja"]));
            }
            set {
                this["AutoOknoDocelowePozycja"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        [SettingsManageability(SettingsManageability.Roaming)]
        public bool OknoGlowneFull {
            get {
                return ((bool)(this["OknoGlowneFull"]));
            }
            set {
                this["OknoGlowneFull"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        [SettingsManageability(SettingsManageability.Roaming)]
        public bool OknoGlowneTop {
            get {
                return ((bool)(this["OknoGlowneTop"]));
            }
            set {
                this["OknoGlowneTop"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        [SettingsManageability(SettingsManageability.Roaming)]
        public bool OknoDoceloweFull {
            get {
                return ((bool)(this["OknoDoceloweFull"]));
            }
            set {
                this["OknoDoceloweFull"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        [SettingsManageability(SettingsManageability.Roaming)]
        public bool OknoDoceloweTop {
            get {
                return ((bool)(this["OknoDoceloweTop"]));
            }
            set {
                this["OknoDoceloweTop"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        [SettingsManageability(SettingsManageability.Roaming)]
        public bool OknoGlowneKeysNumbers {
            get {
                return ((bool)(this["OknoGlowneKeysNumbers"]));
            }
            set {
                this["OknoGlowneKeysNumbers"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        [SettingsManageability(SettingsManageability.Roaming)]
        public bool OknoGlowneKeysArrows {
            get {
                return ((bool)(this["OknoGlowneKeysArrows"]));
            }
            set {
                this["OknoGlowneKeysArrows"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        [SettingsManageability(SettingsManageability.Roaming)]
        public bool OknoDoceloweHideCursor {
            get {
                return ((bool)(this["OknoDoceloweHideCursor"]));
            }
            set {
                this["OknoDoceloweHideCursor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0.5")]
        [SettingsManageability(SettingsManageability.Roaming)]
        public decimal ScreenFadeSpeed {
            get {
                return ((decimal)(this["ScreenFadeSpeed"]));
            }
            set {
                this["ScreenFadeSpeed"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("White")]
        [SettingsManageability(SettingsManageability.Roaming)]
        public Color ScreenForegroundColor {
            get {
                return ((Color)(this["ScreenForegroundColor"]));
            }
            set {
                this["ScreenForegroundColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Black")]
        [SettingsManageability(SettingsManageability.Roaming)]
        public Color ScreenBackgroundColor {
            get {
                return ((Color)(this["ScreenBackgroundColor"]));
            }
            set {
                this["ScreenBackgroundColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("OpenRecent")]
        [SettingsManageability(SettingsManageability.Roaming)]
        public StartupAction GeneralStartAction {
            get {
                return ((StartupAction)(this["GeneralStartAction"]));
            }
            set {
                this["GeneralStartAction"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        [SettingsManageability(SettingsManageability.Roaming)]
        public string GeneralStartPath {
            get {
                return ((string)(this["GeneralStartPath"]));
            }
            set {
                this["GeneralStartPath"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        [SettingsManageability(SettingsManageability.Roaming)]
        public bool GeneralHistoryEnabled {
            get {
                return ((bool)(this["GeneralHistoryEnabled"]));
            }
            set {
                this["GeneralHistoryEnabled"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("5")]
        [SettingsManageability(SettingsManageability.Roaming)]
        public int GeneralHistoryPoints {
            get {
                return ((int)(this["GeneralHistoryPoints"]));
            }
            set {
                this["GeneralHistoryPoints"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0, 0")]
        public Size AutoOknoDoceloweRozmiar {
            get {
                return ((Size)(this["AutoOknoDoceloweRozmiar"]));
            }
            set {
                this["AutoOknoDoceloweRozmiar"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0, 0")]
        public Size AutoOknoGlowneRozmiar {
            get {
                return ((Size)(this["AutoOknoGlowneRozmiar"]));
            }
            set {
                this["AutoOknoGlowneRozmiar"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool AutoOknoGlowneMaximized {
            get {
                return ((bool)(this["AutoOknoGlowneMaximized"]));
            }
            set {
                this["AutoOknoGlowneMaximized"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool AutoOknoDoceloweMaximized {
            get {
                return ((bool)(this["AutoOknoDoceloweMaximized"]));
            }
            set {
                this["AutoOknoDoceloweMaximized"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        [SettingsManageability(SettingsManageability.Roaming)]
        public bool OknoGlowneInnePokazujPelnaSciezkeArchiwum {
            get {
                return ((bool)(this["OknoGlowneInnePokazujPelnaSciezkeArchiwum"]));
            }
            set {
                this["OknoGlowneInnePokazujPelnaSciezkeArchiwum"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        [SettingsManageability(SettingsManageability.Roaming)]
        public bool OknoGlowneInnePokazujPasekPostepuPrzejscia {
            get {
                return ((bool)(this["OknoGlowneInnePokazujPasekPostepuPrzejscia"]));
            }
            set {
                this["OknoGlowneInnePokazujPasekPostepuPrzejscia"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        [SettingsManageability(SettingsManageability.Roaming)]
        public bool GeneralInneDostepZewnetrznyDoArchiwum {
            get {
                return ((bool)(this["GeneralInneDostepZewnetrznyDoArchiwum"]));
            }
            set {
                this["GeneralInneDostepZewnetrznyDoArchiwum"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        [SettingsManageability(SettingsManageability.Roaming)]
        public bool GeneralInneSprawdzajZewnetrzneZmiany {
            get {
                return ((bool)(this["GeneralInneSprawdzajZewnetrzneZmiany"]));
            }
            set {
                this["GeneralInneSprawdzajZewnetrzneZmiany"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        [SettingsManageability(SettingsManageability.Roaming)]
        public bool _FirstStartCompleted {
            get {
                return ((bool)(this["_FirstStartCompleted"]));
            }
            set {
                this["_FirstStartCompleted"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        [SettingsManageability(SettingsManageability.Roaming)]
        public string OtwarteArchiwum {
            get {
                return ((string)(this["OtwarteArchiwum"]));
            }
            set {
                this["OtwarteArchiwum"] = value;
            }
        }
        
        [UserScopedSetting()]
        [SettingsProvider(typeof(PortableSettingsProvider.PortableSettingsProvider))]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Example Song Archive.zip</string>\r\n</ArrayOfString>")]
        [SettingsManageability(SettingsManageability.Roaming)]
        public StringCollection AutoRecentItems {
            get {
                return ((StringCollection)(this["AutoRecentItems"]));
            }
            set {
                this["AutoRecentItems"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool ScreenFontBold {
            get {
                return ((bool)(this["ScreenFontBold"]));
            }
            set {
                this["ScreenFontBold"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool ScreenFontItalic {
            get {
                return ((bool)(this["ScreenFontItalic"]));
            }
            set {
                this["ScreenFontItalic"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool ScreenFontUnderline {
            get {
                return ((bool)(this["ScreenFontUnderline"]));
            }
            set {
                this["ScreenFontUnderline"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string ScreenImagePath {
            get {
                return ((string)(this["ScreenImagePath"]));
            }
            set {
                this["ScreenImagePath"] = value;
            }
        }
    }
}
